# The build-stage image:
FROM nanozoo/pycoqc:2.5.0.23--320ecc7@sha256:2fd6c8b81bcbec85c1cc9b202faf45f23935b893c9bea59e1cac230cf18f578b AS build

################## METADATA ######################
LABEL maintainer="camille.clouard@scilifelab.uu.se"
LABEL version=2.5.0.23
LABEL dorado=2.5.0.23
