# The build-stage image:
FROM  ensemblorg/ensembl-vep:release_111.0

################## METADATA ######################
LABEL maintainer="patrik.smeds@scilifelab.uu.se"
LABEL version=111.0
LABEL ensembl-vep=111.0
