# The build-stage image:
FROM  ensemblorg/ensembl-vep:release_116.0

################## METADATA ######################
LABEL maintainer="jonas.almlof@scilifelab.uu.se,patrik.smeds@scilifelab.uu.se"
LABEL version=116.0
LABEL ensembl-vep=116.0
