# The build-stage image:
FROM  trinityctat/starfusion:1.15.1

################## METADATA ######################
LABEL maintainer="nina.hollfelder@scilifelab.uu.se"
LABEL version=1.15.1
LABEL star-fusion=1.15.1
