# The build-stage image:
FROM ontresearch/dorado@sha256:8c0cdf8d4dfb3ffbbc34782affdcb215c0d1dfaa1372f1672b264064dd0d8e5a AS build

################## METADATA ######################
LABEL maintainer="camille.clouard@scilifelab.uu.se"
LABEL version=2.0.0
LABEL dorado=2.0.0
