# The build-stage image:
FROM ontresearch/dorado:sha38b4ce849afa13eac8075f0b41cecd30799f169b AS build

################## METADATA ######################
LABEL maintainer="camille.clouard@scilifelab.uu.se"
LABEL version=2.0.0
LABEL dorado=2.0.0
