# The build-stage image:
FROM ontresearch/dorado:shae423e761540b9d08b526a1eb32faf498f32e8f22 AS build

################## METADATA ######################
LABEL maintainer="camille.clouard@scilifelab.uu.se"
LABEL version=1.1.1
LABEL dorado=1.1.1
