# The build-stage image:
FROM ontresearch/dorado@sha256:1a98a3d8a5341d98bd84dd41ce2bc2a5a2dae5cb31268d0b3aff9dfec52defd6 AS build

################## METADATA ######################
LABEL maintainer="camille.clouard@scilifelab.uu.se"
LABEL version=1.1.1
LABEL dorado=1.1.1
