# The build-stage image:
FROM  ensemblorg/ensembl-vep:release_109.3

################## METADATA ######################
LABEL maintainer="patrik.smeds@scilifelab.uu.se"
LABEL version=109.3
LABEL ensembl-vep=109.3
