# The build-stage image:
FROM ontresearch/dorado:shac8f356489fa8b44b31beba841b84d2879de2088e AS build

################## METADATA ######################
LABEL maintainer="camille.clouard@scilifelab.uu.se"
LABEL version=1.4.0
LABEL dorado=1.4.0
