# The build-stage image:
FROM ontresearch/dorado@sha256:6d875196de11126aa952da0075dae8fa2aabef13a6f6c4f93c2ac416de9d94a8 AS build

################## METADATA ######################
LABEL maintainer="camille.clouard@scilifelab.uu.se"
LABEL version=1.4.0
LABEL dorado=1.4.0
