FROM python:3.8-slim

RUN pip install multiqc==1.11 multiqc_cgs==0.2

################## METADATA ######################
LABEL VERSION=1.11
LABEL multiqc=1.11
LABEL multiqc_cgs=0.2
################## MAINTAINER ######################
MAINTAINER Patrik Smeds <patrik.smeds@scilifelab.uu.se>

