FROM python:3.8-slim
RUN pip install --no-cache-dir multiqc==1.11 multiqc_cgs==0.2

################## METADATA ######################
LABEL maintainer="patrik.smeds@scilifelab.uu.se"
LABEL version=1.11
LABEL multiqc=1.11
LABEL multiqc-cgs=0.2
