ARG PURECN_VERSION=2.2.0

FROM markusriester/purecn:${PURECN_VERSION}

ARG PURECN_VERSION

################## METADATA ######################
LABEL maintainer="erik.demitz-helin@gu.se"
LABEL version=${PURECN_VERSION}
LABEL purecn=${PURECN_VERSION}

CMD ["/bin/bash"]
