name: Lint Dockerfile

on:
  push

jobs:
  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      - 
        name: Lint Dockerfile
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: "Dockerfile"
          recursive: true
