# The build-stage image:
FROM  ensemblorg/ensembl-vep:release_107.0

################## METADATA ######################
LABEL maintainer="patrik.smeds@scilifelab.uu.se"
LABEL version=107
LABEL ensembl-vep=107

